# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1ed9a62f37130e78e287fbcdfa26f3d842c26609124bf213aafcfe08c2e631bb4e7e7d9e584e3694166c0bca72ca7fdc256f44d3ad1b0380ba58538704bad8a

test:
  secret_key_base: 1e2acc461c33fdb61a85035bf6b3b82c9b9c3c63299a364ffa345a31a0cf1d52d53be185c32ac4ce0b750292420d8f814def09e9ef1c157516c5443b65473e8e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
